### ISSUE TITLE
Blizzard Games

### ISSUE THREAD

**Issue by j-mes** [dr-slash/icons-flat-osx#20]
Firstly, I'd like to say... what a fantastic collection of icons that you have created. I was wondering if you had plans to do the following icons for what's listed below:

- World of Warcraft
- Warcraft 3: Reign of Chaos
- Warcraft 3: The Frozen Throne
- Diablo 2
- Diablo 3
- Heroes of the Storm
- Battle.net Launcher

Keep up the great work either way :+1:

**Comment by dr-slash** [comment]
Icons Added ;)
