### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by bluetidepro** [dr-slash/icons-flat-osx#28]
Great list! Here are a few that I would love to have added!

- 3Hub - [http://www.3hubapp.com/](http://www.3hubapp.com/)
- ImageOptim - [https://imageoptim.com/](https://imageoptim.com/)
- Dash - [http://kapeli.com/dash](http://kapeli.com/dash)
- ProCSSor - [http://procssorapp.com/](http://procssorapp.com/)
- FileZilla - [https://filezilla-project.org/](https://filezilla-project.org/) (referenced in #25)

**Comment by dr-slash** [comment]
hi, finally did it, icons added :)
