### ISSUE TITLE
Developer & app icon requests

### ISSUE THREAD

**Issue by obuiron** [dr-slash/icons-flat-osx#30]
Hi @dr-slash ,

Your icon set, is really awesome !

Could you add some dev icon : 
<s>Android Studio -  <a href="http://i.utdstc.com/icons/256/android-studio.png">icon</a></s>
<s>RubyMine - <a href="https://www.jetbrains.com/ruby/">website</a></s>
<s>TextWrangler - <a href="http://upload.wikimedia.org/wikipedia/fr/e/e8/TextWrangler.png">icon</a></
<s>Shazam - <a href="http://www.shazam.com/">icon</a></s>

 it's can be pretty cool :smile: 

Thanks for your amazing icon set, keep going :wink:

**Comment by dr-slash** [comment]
Hi! All icons added! Thx for kind comment :)
