### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by iwhitfield** [dr-slash/icons-flat-osx#32]
Fantastic, best icon set I have seen. Ever. Here are a few I have that aren't in there though, and I think people would like.

* <s>CloudApp</s>
* <s>Webstorm (by IDEA)</s>
* <s>Keka</s>
* <s>Flowdock</s>
* <s>Genymotion</s>
* <s>OnmiPlan</s>
* <s>Pocket</s>
* <s>Runescape</s>
* <s>Tor</s>
* <s>last.fm</s>

Wondering if any of the above are on the TODO list? If not, would gladly donate a few $$$ these added - it's all I need to have all my applications covered! ;).

**Comment by dr-slash** [comment]
Icons Added! Thx for kind comment :)
