### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by bluetidepro** [dr-slash/icons-flat-osx#35]
Thanks for adding a bunch more icons. Here is a few others I came across that are pretty popular, and may be worth adding.

Apps:
- <s>Hipchat</s> - [https://www.hipchat.com/](https://www.hipchat.com/)
- <s>Flamingo</s>  - [http://flamingo.im/](http://flamingo.im/)
- <s>Adobe Fireworks - [https://creative.adobe.com/products/fireworks](https://creative.adobe.com/products/fireworks)</s>
- <s>Google Drive - [https://www.google.com/drive/](https://www.google.com/drive/)</s>
    - <s>(folder & app)</s>
- <s>Moom</s> - [http://manytricks.com/moom/](http://manytricks.com/moom/)
- <s>Native Apple Maps</s> - [https://www.apple.com/ios/maps/](https://www.apple.com/ios/maps/)
- <s>Native Dashboard</s>
- <s>Droplr</s> - [https://droplr.com/](https://droplr.com/)

Also, what about the idea of adding your PS/Sketch/AI template you are using to generate these? Maybe add a little something to the "readme" so we can also contribute and help make icons with you! If that interests you... :)

Thanks again for all the hard work!

**Comment by bluetidepro** [comment]
Here is another good one (popular) to add:

* SourceTree - http://www.sourcetreeapp.com/

**Comment by dr-slash** [comment]
Icons + Template + Instructions online ;)
