### ISSUE TITLE
icon requests

### ISSUE THREAD

**Issue by dzogchungpa** [dr-slash/icons-flat-osx#36]
wow, these are gorgeous. just a few requests for apps I use frequently (and I think others do as well):

- <s>Wunderlist</s>
- <s>Sunrise</s>
- <s>Anki
- SMITE > Not an osx app
- <s>Mailbox</s>
- <s>Instacast</s>

cheers!

**Comment by jacobyyoung** [comment]
Seconding Wanderlust and Mailbox. That would be wonderful!

**Comment by dr-slash** [comment]
Icons added ;)
