### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by zamoradan** [dr-slash/icons-flat-osx#37]
First I'd like to say long time fan, extremely big fan of your art style (including your tumblr themes). I'd be glad if you could icons for:

*League of Legends - [Icon](https://hdgameplay.com/uploads/games/LoL_icon.png) [Website](http://na.leagueoflegends.com)
*MatLab 2014 - [Icon](http://i.stack.imgur.com/zLI11.gif) [Website](http://www.mathworks.com/products/matlab/)
*Guild Wars 2 - [Icon](http://fc03.deviantart.net/fs70/f/2012/151/1/d/guild_wars_2_v2_by_polishxcii-d51tsmu.png) [Website](https://www.guildwars2.com/en/)
*Parallels Desktop - [Icon](http://i1-news.softpedia-static.com/images/news2/Parallels-Desktop-7-for-Mac-Now-Available-to-General-Population-2.jpg) [Website](http://www.parallels.com/ca/cross-platform-solutions/)
*uTorrent - [Icon](https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/uTorrent_alt.png) [Website](http://www.utorrent.com)
*SoundCloud - [Icon](https://lh4.ggpht.com/2szV51du96rRZhQydA2gKYHUUxyo_cPmRItgPTg2i-1yD1sly7hhkOCSn36KVU_sMhw=w300) [Website](https://soundcloud.com/stream)

**Comment by tvdisko** [comment]
Hi there,

Just spotted your icon collection and it looks great.  Very nice work.  I'm wondering if you could make some icons for the following:

Soulseek: http://www.soulseekqt.net/news/ (though a better icon might be derived from something like this: https://remake23.deviantart.com/art/Soulseek-131951997)
Amadeus Pro: http://www.hairersoft.com/pro.html
Onyx: http://www.titanium.free.fr/onyx.html

Cheers,
Geoff

**Comment by dr-slash** [comment]
Added to todo list
