### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by TurtleDuck** [dr-slash/icons-flat-osx#41]
Could you add these please:

<s>LibreOffice</s> Same as OpenOffice
<s>Chrome app launcher</s>
Bitcoin-Qt
<s>Rescuetime</s>
<s>Onenote</s>
<s>Pushbullet</s>
Python Folder & Python IDE

And lastly, maybe a guide on how to change file icons?
Thank you.

**Comment by dr-slash** [comment]
Done somes, rest added to todolist
