### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by mtesseracttech** [dr-slash/icons-flat-osx#47]
Hey, the icons look amazing, I love them, I see almost all Jetbrains applications are there, but CLion and PHPStorm are missing, it would be great if the set was completed by adding them. :D
And if possible, an icon for visual studio, I know it's not a native OSX application, but I know many people who use Visual studio on parallels, and it has that terrible out of place icon.

**Comment by dr-slash** [comment]
Added to todo list
