### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by 7heRealDeal** [dr-slash/icons-flat-osx#48]
Salut, avant tout félicitations, ce set d'icônes est de qualité. Possible de rajouter svp : 

En app système :
Stickies
Airport Utility
Console
Disk Utility
System Informations
X11
Dictionary
Automator
Game Center
Bluetooth File Transfer

Système :
Un "device" SSD

En app :
Tumblr
Awaken
AppDelete
Toast Titanium
MacGameStore
Flickery
Bowtie
EasyFind
Candybar
Movist
PlistEditPro
Slipcover
UnRarX
Viscosity
GeekBench 3
Little Snitch
BBEdit

En dossier :
Toast Titanium
MS Office
MacGameStore

Quelques icônes effectivement :)

Cordialement,
Nico

**Comment by dr-slash** [comment]
Ajouté a ma liste de tache (qui ressemble a un annuaire ;) )
