### ISSUE TITLE
Check in a LICENSE file to GitHub

### ISSUE THREAD

**Issue by jawnsy** [dr-slash/icons-flat-osx#56]
Hi,

Thanks for producing such gorgeous icons and releasing them under an open-source license!

I see the following statement on the [official web site for the icons](https://drslash.com/flat-osx-pack/):

> FLAT OS by DrSlash.com is licensed under a Creative Commons Attribution – NonCommercial 4.0 International License.

It would be nice to add a statement to the README indicating the license and also have a copy of it as a LICENSE file. This is standard practice on GitHub and will help others understand their rights and obligations with respect to their use of your icons. It may even encourage other designers to contribute.

Cheers,

Jonathan

**Comment by dr-slash** [comment]
Hi,

Thanks for the advice :) i added statement & file

Cheers,

Jean
