### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ddulic** [dr-slash/icons-flat-osx#59]
First of all thank you for the amazing icon pack. Here are some of the apps I use on a daily basis that don't have icons and aren't in the requested icons. Thanks.

Commander One
Malwarebytes
Unified Remote
Tunnelbear
Xampp
Pacifict

**Comment by dr-slash** [comment]
hi, cant find an app with "Pacifict" name, please provide a link ;)

**Comment by ddulic** [comment]
My bad, got a typo there. The correct name is "Pacifist" and [here](https://www.charlessoft.com/) is the link :)

**Comment by dr-slash** [comment]
request complete, enjoy ;)
