### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by chadrien** [dr-slash/icons-flat-osx#60]
Hey,

Just opening as I'm not really comfortable/an expert with the CC license. I'm currently building an open source, free application for ios/android under the MIT license for Heroes of the Storm (https://github.com/chadrien/app-of-the-storm). Is it ok to use your HotS icon for my app icon?

Your license is CC non commercial, so I think it would be OK as I want to release the app for free and won't include any add in it (I hate ads in apps / my goal is not to make a profit out of it, simply to make hots players' life easier). I just wanted to be sure.

Anyway I just found this repo randomly from Google, and I must admit that your work is awesome ♥️! Congrats!

**Comment by dr-slash** [comment]
Hi,
i prefer to make you a custom icon for your app for free than using this one, whats your color scheme of your app?
Sorry for my rusty english :)

cheers

**Comment by chadrien** [comment]
Wow, thank you! The main (background) color is `#0d0119` (taken from the official HotS background).

I'm on my mobile right now, but I'll join a screenshot of the WIP as soon as I can

**Comment by chadrien** [comment]
As promised, here is the current WIP

![screenshot_20160614-110813](https://cloud.githubusercontent.com/assets/1788218/16037906/e59a4e4a-3222-11e6-9678-5f2c693ff63e.png)

Thanks again for the help!

**Comment by dr-slash** [comment]
Hi,

sorry for been so long with this (got a kid, moved to another flat...) but here it is, you can download source files here [https://we.tl/NogIDaLPXN](https://we.tl/NogIDaLPXN) contains .ai .png .svg files both square and circle version.

cheers

**Comment by chadrien** [comment]
Hey,

I can totally understand, currently preparing to move to Finland myself, so I know the struggle 😄 
Thanks a lot anyway! That's awesome work!
