### ISSUE TITLE
Icon Request - Robokill

### ISSUE THREAD

**Issue by CaptainXD** [dr-slash/icons-flat-osx#65]
Link: https://itunes.apple.com/us/app/robokill-rescue-titan-prime/id429897659?mt=12

**Comment by AbhimanyuAryan** [comment]
There's already a Issue for icon request post there. Close this one

**Comment by CaptainXD** [comment]
There have been dozens of previous icon requests with their own thread. If Dr. Slash would like me to remove this I will do so. Until then, I'm leaving it up.

**Comment by dr-slash** [comment]
Added ;)
