### ISSUE TITLE
Icon Request - WhatsApp

### ISSUE THREAD

**Issue by oyed** [dr-slash/icons-flat-osx#66]

**Comment by AbhimanyuAryan** [comment]
there's already a open issue for icon request. Post there...don't spam -_-

**Comment by oyed** [comment]
I think you're misusing the word "spam", and **try reading the actual README file**. I quote:

> Icons Request

Please open an issue here. Issues through emails and Facebook are not fulfilled.

**Comment by AbhimanyuAryan** [comment]
check this issue "Icons requests - To Do List Icon request"....close rest of your issues coz its hard to manage separate issue for one person

**Comment by oyed** [comment]
The **To-do** List (Promptly named "**To-do** list") is a **To-do** list of things **To-do**. As stated in the README, and as I've previously made now fulfilled icon requests, this issue is completely fine.

**Comment by dr-slash** [comment]
just chill dudes, i'm aware of requests wherever they are ;)

**Comment by oyed** [comment]
Thanks @dr-slash ^^

**Comment by dr-slash** [comment]
Icon Added ;)
