### ISSUE TITLE
Icon Request - mSecure

### ISSUE THREAD

**Issue by luminousrubyist** [dr-slash/icons-flat-osx#71]
I've used your icons for several months now, and I want to thank you for creating and maintaining them! Your work is superb.

Could you create an icon for [mSecure](https://www.msecure.com/)? I've swept through this repository and other requests and haven't seen it. Thanks again for making all our docks a bit prettier!

**Comment by dr-slash** [comment]
Thanks for your feedback :) added msecure to todo list!
