### ISSUE TITLE
CLion icon doesn't change

### ISSUE THREAD

**Issue by singalen** [dr-slash/icons-flat-osx#74]
I'm changing app icons to ICNS files using the "Get info" - paste icon" method on OS X 10.11.6.
I could change PyCharm, Intellij IDEA, but no longer can change CLion: it reverts to the default icon as soon as I launch it.
Maybe it has something to do with the available icon sizes and the recent OS X changes?

Thanks for the great work!

**Comment by dr-slash** [comment]
Hi, unfortunately the way you change icons have changed in Sierra, you have to [turn off SIP](https://www.igeeksblog.com/how-to-disable-system-integrity-protection-on-mac/) and use [Liteicon](https://freemacsoft.net/liteicon/), let me know if it solves your problem,

kind regards
Jean

**Comment by singalen** [comment]
I'm on El Capitan still (10.11.6).
Do I have to turn off SIP for non-system application?

**Comment by oyed** [comment]
Yes, SIP was introduced/enforced in El Capitan.
